@startuml

boundary Dashboard
control TicketCtrl
entity TicketRepository

==Create a ticket from Complain==

Dashboard -> TicketCtrl: CreateTicketFromComplain
TicketCtrl -> TicketRepository: CreateTicketd
TicketRepository -> Dashboard: Message

==Create a ticket from Multiple Complains==

Dashboard -> TicketCtrl: CreateTicketFromMultipleComplain
TicketCtrl -> TicketRepository: CreateTicketd
TicketRepository -> Dashboard: Message

@enduml