import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import { RoleBasedSidebar } from "./sidebar/RoleBasedSidebar";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  console.log("session", session);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: "#363636",
                color: "#fff",
              },
              success: {
                duration: 3000,
                style: {
                  background: "#10B981",
                },
              },
              error: {
                duration: 5000,
                style: {
                  background: "#EF4444",
                },
              },
            }}
          />
          <NavBar session={session} />
          <main className="flex max-w-screen-2xl mx-auto pt-10 ">
            <div className="w-1/6">
              <RoleBasedSidebar session={session} />
            </div>
            <div className="w-5/6">{children}</div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
