import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import { SideBar } from "./sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />

        <main className="flex mx-auto px-5 pt-10">
          <div className="w-1/6">
            <SideBar />
          </div>
          <div className="w-5/6">{children}</div>
        </main>
      </body>
    </html>
  );
}
