@startuml

boundary MapScreen
entity LocationService
control ComplainCtrl
entity ComplainRepository
database PSMDB

MapScreen -> LocationService: GetNearLightPosts (location)
LocationService -> MapScreen: LightPostArray[]


MapScreen -> ComplainCtrl: AddComplain
ComplainCtrl -> ComplainRepository: AddComplain

ComplainRepository -> PSMDB: persistComplain

' ==test==
' boundary MapScreen
' entity LocationService

@enduml


