	
@startchen

entity User {
    UserNo
    FirstName
    LastName
    Mobile
}


entity Ticket {
    TicketId
    Name
    Title
    Detail
    Note
    CreatedDate
    UserId
}

relationship Assign_To{

}

User -1- Assign_To
Assign_To -N- Ticket

entity Client {
    ClientId
    Name
    Mobile
}

entity Complaint{
    ComplainId
    Name
    Detail
    CreatedDate
    UpdatedDate
}

relationship Raise{

}

Client -1- Raise
Raise -N- Complaint

relationship Creates{

}


Ticket -1- Creates
Creates -N- Complaint

entity LightPostComplint{
    LightPostNo
}

entity GrabageComplaint{
    GarbagePointNo
}

Complaint ->- LightPostComplint
Complaint ->- GrabageComplaint

entity LightPost{
    LightPostNumber
    Latitude
    Longitue
}

relationship Relates_To_Light{

}


LightPost -1- Relates_To_Light
Relates_To_Light -N- LightPostComplint

entity Project{
    Id 
    Name 
    description
    Type
    Specification 
    StartDate
    EndDate
    Status
    Location
    LocationNote
    Latitude
    Longitude
    EstimatedCost
    AwadedTenderId
    TenderOpeningDate
    TenderClosingDate
}

entity ProjectStandard {
    Id 
    Title 
    Note
    IsManditory
    ProjectId
}

relationship adhireTo {

}

Project -1- adhireTo
adhireTo -N- ProjectCondition

entity Tender{
    Id
    Name
    Note
    CompanyId
    BidAmount
    ProjectId  
}

relationship TenderFor{

}

Project -1- TenderFor
TenderFor -N- Tender

entity ProjectComplain{
    ProjectId   
}

entity Company{
    Id
    Name
    Address
    
}

@endchen