entity Ticket {
    TicketId
    Subject
    Detail
    Note
    Status
    Type
    UserId
}
entity Tender {
    TenderId
    Subject
    Note
    BidAmount
    SubmittedDate
    ProjectId
    CompanyId
}
entity Vehical {
    VehicalNo
    RegistrationNo
    Model
    Brand
    Year
}
entity RidePoint {
    RidePointId
    Latitude
    Longitude
    PointTime
    RideId
}

Ride -1- RidePoint
RidePoint -N- Ride
entity Ride {
    RideId
    StartTime
    EndTime
    Type
    Notes
    DriverNo
    VehicalNo
    RegionNo
}
entity RoutePoint {
    RoutePointId
    PointName
    Latitude
    Longitude
    RouteNo
}

Route -1- RoutePoint
RoutePoint -N- Route
entity Route {
    RouteNo
    Name
    Distance
}
entity ProjectStandard {
    ProjectStandardId
    Standard
    Note
    IsMandatory
    ProjectId
}

Project -1- ProjectStandard
ProjectStandard -N- Project
entity GeneralComplain {
    IsPrivate
}

GeneralComplain --|> Workpackage
entity Region {
    RegionNo
    Name
    Note
}
entity GCShedule {
    GCSheduleId
    Day
    Type
    Time
    RegionNo
}

Region -1- GCShedule
GCShedule -N- Region

entity GarbageComplain {
    GarbagePointNo  
}

Workpackage -1- GarbageComplain
GarbageComplain -N- Workpackage
entity Driver {
    UserId
    FirstName
    LastName
    Mobile
    LicenseNo
    ExpireDate
}
entity Comment {
    CommentId
    Text
    WorkpackageId

}

Workpackage -1- Comment
Comment -N- Workpackage
    
@startchen

entity User {
    UserId
    FirstName
    LastName
    Mobile
    Email
    City
}


entity Ticket {
    TicketId
    Name
    Title
    Detail
    Note
    CreatedDate
    UserId
}

relationship Assign_To{

}

User -1- Assign_To
Assign_To -N- Ticket

entity Client {
    ClientId
    FirstName
    LastName
    Mobile
    Email
    AddressLine1
    AddressLine2
    City
}

entity Workpackage{
    WorkpackageId
    Subject
    Detail
    Status
    ClientId
    WorkpackageType

}

relationship Raise{

}

Client -1- Raise
Raise -N- Workpackage

relationship Creates{

}


Ticket -1- Creates
Creates -N- Workpackage

entity LightPostComplain{
    LightPostNumber
}

entity GrabageComplaint{
    GarbagePointNo
}

Workpackage ->- LightPostComplain
Workpackage ->- GrabageComplaint

entity LightPost{
    LightPostNumber
    Latitude
    Longitue
}

relationship Relates_To_Light{

}


LightPost -1- Relates_To_Light
Relates_To_Light -N- LightPostComplain

entity Project {
    Id
    Subject
    Description
    Type
    SpecificationDocument
    StartDate
    EndDate
    Status
    Location
    LocationNote
    City
    Latitude
    Longitude
    EstimatedCost
    AwadedTenderId
    TenderOpeningDate
    TenderClosingDate
}

entity ProjectStandard {
    Id 
    Title 
    Note
    IsManditory
    ProjectId
}

relationship adhireTo {

}

Project -1- adhireTo
adhireTo -N- ProjectCondition

entity Tender{
    Id
    Name
    Note
    CompanyId
    BidAmount
    ProjectId  
}

relationship TenderFor{

}

Project -1- TenderFor
TenderFor -N- Tender

entity ProjectComplain{
    ProjectId   
}

entity Company{
    CompanyId
    Name
    AddressLine1
    AddressLine2
    City
    Mobile
}




@endchen