@startuml

boundary Dashboard
control ComplainCtrl
entity ComplainRepo

Dashboard -> ComplainCtrl: LoadRecentActiveComplains
ComplainCtrl -> ComplainRepo: GroupBy(Name, PostNo)
ComplainRepo -> Dashboard: RecentActiveComplain[]

@enduml
