// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSMDataAccess;

#nullable disable

namespace PSMDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSMModel.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = "1",
                            AddressLine1 = "123 Main St",
                            AddressLine2 = "Apt 4B",
                            City = "Colombo",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            IsActive = true
                        },
                        new
                        {
                            ClientId = "2",
                            AddressLine1 = "456 Lake Rd",
                            City = "Kandy",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WorkpackageId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkpackageId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PSMModel.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            AddressLine1 = "123 Main St",
                            City = "Colombo",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            IsActive = true,
                            Mobile = "0771234567",
                            Name = "Maga"
                        },
                        new
                        {
                            CompanyId = 2,
                            AddressLine1 = "123 Main St",
                            City = "Gampaha",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            IsActive = true,
                            Mobile = "0779876543",
                            Name = "Access Construction"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.GCShedule", b =>
                {
                    b.Property<int>("GCSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GCSheduleId"));

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RegionNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("GCSheduleId");

                    b.HasIndex("RegionNo");

                    b.ToTable("GCShedules");

                    b.HasData(
                        new
                        {
                            GCSheduleId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Monday",
                            IsActive = true,
                            RegionNo = "R001",
                            Time = "Morning",
                            Type = "Plastic"
                        },
                        new
                        {
                            GCSheduleId = 2,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Tuesday",
                            IsActive = true,
                            RegionNo = "R001",
                            Time = "Morning",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 3,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Wednesday",
                            IsActive = true,
                            RegionNo = "R001",
                            Time = "Morning",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 4,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Thursday",
                            IsActive = true,
                            RegionNo = "R001",
                            Time = "Afternoon",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 5,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Friday",
                            IsActive = true,
                            RegionNo = "R001",
                            Time = "Morning",
                            Type = "Paper"
                        },
                        new
                        {
                            GCSheduleId = 6,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Monday",
                            IsActive = true,
                            RegionNo = "R002",
                            Time = "Morning",
                            Type = "Plastic"
                        },
                        new
                        {
                            GCSheduleId = 7,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Tuesday",
                            IsActive = true,
                            RegionNo = "R002",
                            Time = "Morning",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 8,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Wednesday",
                            IsActive = true,
                            RegionNo = "R002",
                            Time = "Morning",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 9,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Thursday",
                            IsActive = true,
                            RegionNo = "R002",
                            Time = "Afternoon",
                            Type = "Garbage"
                        },
                        new
                        {
                            GCSheduleId = 10,
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Day = "Friday",
                            IsActive = true,
                            RegionNo = "R002",
                            Time = "Morning",
                            Type = "Paper"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.LightPost", b =>
                {
                    b.Property<string>("LightPostNumber")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("LightPostNumber");

                    b.ToTable("LightPosts");

                    b.HasData(
                        new
                        {
                            LightPostNumber = "LP001",
                            Latitude = 7.0259340000000003,
                            Longitude = 80.026858000000004
                        },
                        new
                        {
                            LightPostNumber = "LP002",
                            Latitude = 7.027679,
                            Longitude = 80.027620999999996
                        },
                        new
                        {
                            LightPostNumber = "LP003",
                            Latitude = 7.0308330000000003,
                            Longitude = 80.028531999999998
                        },
                        new
                        {
                            LightPostNumber = "LP004",
                            Latitude = 7.0330199999999996,
                            Longitude = 80.027282
                        },
                        new
                        {
                            LightPostNumber = "LP005",
                            Latitude = 7.0348280000000001,
                            Longitude = 80.025925999999998
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int?>("WorkpackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("WorkpackageId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PSMModel.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwadedTenderId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LocationNote")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecificationDocument")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDate?>("TenderClosingDate")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("TenderOpeningDate")
                        .HasColumnType("date");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwadedTenderId = 1,
                            City = "Weliveriya",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            Description = "Description for Project Alpha",
                            EndDate = new NodaTime.LocalDate(2023, 12, 31),
                            EstimatedCost = 1000000m,
                            IsActive = true,
                            Latitude = 34.052199999999999,
                            Location = "Location A",
                            LocationNote = "Note for Location A",
                            Longitude = -118.2437,
                            SpecificationDocument = "specification_alpha.pdf",
                            StartDate = new NodaTime.LocalDate(2023, 1, 1),
                            Status = 0,
                            Subject = "Project Alpha",
                            TenderClosingDate = new NodaTime.LocalDate(2023, 1, 30),
                            TenderOpeningDate = new NodaTime.LocalDate(2023, 1, 15),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AwadedTenderId = 2,
                            City = "Ambaraluwa",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            Description = "Weliveriya road project",
                            EndDate = new NodaTime.LocalDate(2023, 12, 31),
                            EstimatedCost = 1000000m,
                            IsActive = true,
                            Latitude = 34.052199999999999,
                            Location = "Location A",
                            LocationNote = "Note for Location A",
                            Longitude = -118.2437,
                            SpecificationDocument = "specification_alpha.pdf",
                            StartDate = new NodaTime.LocalDate(2023, 1, 1),
                            Status = 0,
                            Subject = "Weliveriya road project",
                            TenderClosingDate = new NodaTime.LocalDate(2023, 1, 30),
                            TenderOpeningDate = new NodaTime.LocalDate(2023, 1, 15),
                            Type = 0
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Region", b =>
                {
                    b.Property<string>("RegionNo")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("RegionNo");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionNo = "R001",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Name = "Weliveriya South",
                            Note = "This is a region in Gampaha district."
                        },
                        new
                        {
                            RegionNo = "R002",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Name = "Weliveriya North",
                            Note = "This is a region in Gampaha district."
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Ride", b =>
                {
                    b.Property<int>("RideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RideId"));

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Driver")
                        .HasColumnType("integer");

                    b.Property<int>("DriverNo")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RegionNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VehicalNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RideId");

                    b.HasIndex("RegionNo");

                    b.HasIndex("VehicalNo");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            RideId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(2025, 7, 10, 12, 0),
                            CreatedBy = "1",
                            Driver = 0,
                            DriverNo = 1,
                            IsActive = true,
                            RegionNo = "R001",
                            StartTime = new NodaTime.LocalDateTime(2025, 7, 10, 13, 0),
                            Type = "Paper Collection",
                            VehicalNo = "T01"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.RidePoint", b =>
                {
                    b.Property<int>("RidePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RidePointId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<LocalDateTime>("PointTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.HasKey("RidePointId");

                    b.HasIndex("RideId");

                    b.ToTable("RidePoints");
                });

            modelBuilder.Entity("PSMModel.Models.Route", b =>
                {
                    b.Property<string>("RouteNo")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("RouteNo");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteNo = "R001",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            Distance = 0f,
                            IsActive = true,
                            Name = "Noth Root"
                        },
                        new
                        {
                            RouteNo = "R002",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            Distance = 0f,
                            IsActive = true,
                            Name = "South Root"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.RoutePoint", b =>
                {
                    b.Property<int>("RoutePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoutePointId"));

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("RoutePointId");

                    b.HasIndex("RouteNo");

                    b.ToTable("RoutePoints");

                    b.HasData(
                        new
                        {
                            RoutePointId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.026488999999998,
                            Longitude = 7.0249980000000001,
                            PointName = "maduma bankara vidyalaya",
                            RouteNo = "R001"
                        },
                        new
                        {
                            RoutePointId = 2,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.022924000000003,
                            Longitude = 7.0254649999999996,
                            PointName = "gala gawa",
                            RouteNo = "R001"
                        },
                        new
                        {
                            RoutePointId = 3,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.021614,
                            Longitude = 7.0225910000000002,
                            PointName = "Sewa Piyasa",
                            RouteNo = "R001"
                        },
                        new
                        {
                            RoutePointId = 4,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.023321999999993,
                            Longitude = 7.0228789999999996,
                            PointName = "jayamal oil",
                            RouteNo = "R001"
                        },
                        new
                        {
                            RoutePointId = 5,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.026511999999997,
                            Longitude = 7.0212519999999996,
                            PointName = "bathiya home",
                            RouteNo = "R001"
                        },
                        new
                        {
                            RoutePointId = 6,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Latitude = 80.026774000000003,
                            Longitude = 7.0229679999999997,
                            PointName = "grace health",
                            RouteNo = "R001"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Tender", b =>
                {
                    b.Property<int>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenderId"));

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("SubmittedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("TenderId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tenders");

                    b.HasData(
                        new
                        {
                            TenderId = 1,
                            BidAmount = 500000m,
                            CompanyId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 10, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Note = "This is a tender for Project A",
                            ProjectId = 1,
                            Subject = "Tender for Project A",
                            SubmittedDate = new NodaTime.LocalDateTime(2023, 10, 1, 10, 0)
                        },
                        new
                        {
                            TenderId = 2,
                            BidAmount = 300000m,
                            CompanyId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(2023, 10, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Note = "This is a tender for Project A",
                            ProjectId = 1,
                            Subject = "Tender for Road Construction",
                            SubmittedDate = new NodaTime.LocalDateTime(2023, 10, 1, 10, 0)
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.PrimitiveCollection<List<string>>("Attachments")
                        .HasColumnType("text[]");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Estimation")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TicketWorkpackageType")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Estimation = 0,
                            IsActive = true,
                            Status = 0,
                            Subject = "Fix Light Post LP001",
                            Type = 1,
                            UserId = "1"
                        },
                        new
                        {
                            TicketId = 2,
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "2",
                            Estimation = 0,
                            IsActive = true,
                            Status = 0,
                            Subject = "Fix Light Post LP001 2",
                            Type = 1,
                            UserId = "2"
                        },
                        new
                        {
                            TicketId = 3,
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "2",
                            Estimation = 0,
                            IsActive = true,
                            Status = 0,
                            Subject = "Fix Light Post LP001 3",
                            Type = 1,
                            UserId = "2"
                        },
                        new
                        {
                            TicketId = 4,
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "2",
                            Estimation = 0,
                            IsActive = true,
                            Status = 0,
                            Subject = "Fix Light Post LP001 4",
                            Type = 1,
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.TicketActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int?>("Transition")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketActivities");
                });

            modelBuilder.Entity("PSMModel.Models.TicketHistory", b =>
                {
                    b.Property<int>("TicketHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketHistoryId"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("TicketHistoryId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories");
                });

            modelBuilder.Entity("PSMModel.Models.TicketPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkpackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("WorkpackageId");

                    b.ToTable("TicketPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TicketId = 1,
                            WorkpackageId = 2
                        },
                        new
                        {
                            Id = 2,
                            TicketId = 1,
                            WorkpackageId = 3
                        },
                        new
                        {
                            Id = 3,
                            TicketId = 3,
                            WorkpackageId = 4
                        },
                        new
                        {
                            Id = 4,
                            TicketId = 4,
                            WorkpackageId = 5
                        });
                });

            modelBuilder.Entity("PSMModel.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            City = "Colombo",
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            Mobile = "0777582696"
                        },
                        new
                        {
                            UserId = "2",
                            City = "Galle",
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Email = "kamal@example.com",
                            FirstName = "Kamal",
                            IsActive = true,
                            LastName = "Perera",
                            Mobile = "0147894562"
                        },
                        new
                        {
                            UserId = "3",
                            City = "Kandy",
                            CreatedAt = new NodaTime.LocalDateTime(1, 1, 1, 0, 0),
                            Email = "kumara@example.com",
                            FirstName = "Kumara",
                            IsActive = true,
                            LastName = "Fernando",
                            Mobile = "0117654321"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Vehical", b =>
                {
                    b.Property<string>("VehicalNo")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicalNo");

                    b.ToTable("Vehicals");

                    b.HasData(
                        new
                        {
                            VehicalNo = "T01",
                            Brand = "John Dear",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Model = "T66",
                            RegistrationNo = "GA1234",
                            Year = "1998"
                        },
                        new
                        {
                            VehicalNo = "T02",
                            Brand = "Toyota",
                            CreatedAt = new NodaTime.LocalDateTime(2023, 1, 1, 9, 0),
                            CreatedBy = "1",
                            IsActive = true,
                            Model = "Truch",
                            RegistrationNo = "CAG3456",
                            Year = "2024"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Workpackage", b =>
                {
                    b.Property<int>("WorkpackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkpackageId"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MyProperty")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime?>("RatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("RatingReview")
                        .HasColumnType("text");

                    b.Property<string>("Sentiment")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WorkpackageType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("WorkpackageId");

                    b.HasIndex("ClientId");

                    b.ToTable("Workpackages");

                    b.HasDiscriminator<string>("WorkpackageType").HasValue("Workpackage");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            WorkpackageId = 1,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Detail = "Detail for Work Package 1",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Work Package 1",
                            UpdatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            WorkpackageType = "Workpackage"
                        },
                        new
                        {
                            WorkpackageId = 2,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 7, 1, 10, 0),
                            CreatedBy = "2",
                            Detail = "Detail for Work Package 2",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 2,
                            Subject = "Work Package 2",
                            UpdatedAt = new NodaTime.LocalDateTime(2025, 7, 1, 10, 0),
                            WorkpackageType = "Workpackage"
                        },
                        new
                        {
                            WorkpackageId = 3,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 7, 10, 9, 30),
                            CreatedBy = "3",
                            Detail = "Detail for Work Package 3",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 2,
                            Subject = "Work Package 3",
                            UpdatedAt = new NodaTime.LocalDateTime(2025, 7, 10, 9, 30),
                            WorkpackageType = "Workpackage"
                        },
                        new
                        {
                            WorkpackageId = 4,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 7, 15, 8, 0),
                            CreatedBy = "4",
                            Detail = "Detail for Work Package 4",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Work Package 4",
                            UpdatedAt = new NodaTime.LocalDateTime(2025, 7, 15, 8, 0),
                            WorkpackageType = "Workpackage"
                        },
                        new
                        {
                            WorkpackageId = 5,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 7, 20, 11, 45),
                            CreatedBy = "1",
                            Detail = "Detail for Work Package 5",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Work Package 5",
                            UpdatedAt = new NodaTime.LocalDateTime(2025, 7, 20, 11, 45),
                            WorkpackageType = "Workpackage"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Driver", b =>
                {
                    b.HasBaseType("PSMModel.Models.User");

                    b.Property<LocalDateTime?>("ExpireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Driver");

                    b.HasData(
                        new
                        {
                            UserId = "4",
                            City = "Colombo",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            FirstName = "Upul",
                            IsActive = true,
                            LastName = "Perera",
                            Mobile = "0777582365",
                            ExpireDate = new NodaTime.LocalDateTime(2027, 6, 19, 14, 14),
                            LicenseNo = "2345"
                        },
                        new
                        {
                            UserId = "5",
                            City = "Galle",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            FirstName = "Shantha",
                            IsActive = true,
                            LastName = "Fernando",
                            Mobile = "0147894492",
                            ExpireDate = new NodaTime.LocalDateTime(2028, 6, 19, 14, 14),
                            LicenseNo = "2345"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.GarbageComplain", b =>
                {
                    b.HasBaseType("PSMModel.Models.Workpackage");

                    b.Property<string>("GarbagePointNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GarbageComplain");
                });

            modelBuilder.Entity("PSMModel.Models.GeneralComplain", b =>
                {
                    b.HasBaseType("PSMModel.Models.Workpackage");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("GeneralComplain");

                    b.HasData(
                        new
                        {
                            WorkpackageId = 12,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Detail = "General Complain 1 description",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "General Complain 1",
                            IsPrivate = false
                        });
                });

            modelBuilder.Entity("PSMModel.Models.LightPostComplain", b =>
                {
                    b.HasBaseType("PSMModel.Models.Workpackage");

                    b.Property<string>("LightPostNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LightPostNumber");

                    b.HasDiscriminator().HasValue("LightPostComplain");

                    b.HasData(
                        new
                        {
                            WorkpackageId = 21,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Detail = "Light post not working at Main St.",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Light Post Issue",
                            LightPostNumber = "LP001"
                        },
                        new
                        {
                            WorkpackageId = 22,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Detail = "Light post LP001 is not working 2",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Light Post Issue 2",
                            LightPostNumber = "LP001"
                        },
                        new
                        {
                            WorkpackageId = 23,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 20, 14, 14),
                            CreatedBy = "1",
                            Detail = "Light post LP001 is not working 3",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Light Post Issue 3",
                            LightPostNumber = "LP001"
                        },
                        new
                        {
                            WorkpackageId = 24,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 20, 14, 14),
                            CreatedBy = "1",
                            Detail = "Light post LP002 is not working 4",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Light Post Issue 4",
                            LightPostNumber = "LP002"
                        },
                        new
                        {
                            WorkpackageId = 25,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 20, 14, 14),
                            CreatedBy = "1",
                            Detail = "Light post LP002 is not working 5",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Light Post Issue 5",
                            LightPostNumber = "LP002"
                        });
                });

            modelBuilder.Entity("PSMModel.Models.ProjectComplain", b =>
                {
                    b.HasBaseType("PSMModel.Models.Workpackage");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasIndex("ProjectId");

                    b.HasDiscriminator().HasValue("ProjectComplain");

                    b.HasData(
                        new
                        {
                            WorkpackageId = 31,
                            ClientId = "1",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 19, 14, 14),
                            CreatedBy = "1",
                            Detail = "Project Complain 1 description",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 0,
                            Subject = "Project Complain 1",
                            ProjectId = 1
                        },
                        new
                        {
                            WorkpackageId = 32,
                            ClientId = "2",
                            CreatedAt = new NodaTime.LocalDateTime(2025, 6, 20, 10, 0),
                            CreatedBy = "2",
                            Detail = "Project Complain 2 description",
                            IsActive = true,
                            MyProperty = 0,
                            Status = 2,
                            Subject = "Project Complain 2",
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("PSMModel.Models.Comment", b =>
                {
                    b.HasOne("PSMModel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("PSMModel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("PSMModel.Models.Workpackage", "Workpackage")
                        .WithMany("Comments")
                        .HasForeignKey("WorkpackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");

                    b.Navigation("Workpackage");
                });

            modelBuilder.Entity("PSMModel.Models.GCShedule", b =>
                {
                    b.HasOne("PSMModel.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PSMModel.Models.Notification", b =>
                {
                    b.HasOne("PSMModel.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId");

                    b.HasOne("PSMModel.Models.Workpackage", "Workpackage")
                        .WithMany()
                        .HasForeignKey("WorkpackageId");

                    b.Navigation("Ticket");

                    b.Navigation("Workpackage");
                });

            modelBuilder.Entity("PSMModel.Models.Ride", b =>
                {
                    b.HasOne("PSMModel.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSMModel.Models.Vehical", "Vehical")
                        .WithMany()
                        .HasForeignKey("VehicalNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Vehical");
                });

            modelBuilder.Entity("PSMModel.Models.RidePoint", b =>
                {
                    b.HasOne("PSMModel.Models.Ride", "Ride")
                        .WithMany("RidePoints")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("PSMModel.Models.RoutePoint", b =>
                {
                    b.HasOne("PSMModel.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PSMModel.Models.Tender", b =>
                {
                    b.HasOne("PSMModel.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSMModel.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSMModel.Models.Ticket", b =>
                {
                    b.HasOne("PSMModel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSMModel.Models.TicketActivity", b =>
                {
                    b.HasOne("PSMModel.Models.Ticket", null)
                        .WithMany("Activities")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSMModel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSMModel.Models.TicketHistory", b =>
                {
                    b.HasOne("PSMModel.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("PSMModel.Models.TicketPackage", b =>
                {
                    b.HasOne("PSMModel.Models.Ticket", "Ticket")
                        .WithMany("TicketPackages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSMModel.Models.Workpackage", "Workpackage")
                        .WithMany("TicketPackages")
                        .HasForeignKey("WorkpackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Workpackage");
                });

            modelBuilder.Entity("PSMModel.Models.Workpackage", b =>
                {
                    b.HasOne("PSMModel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PSMModel.Models.LightPostComplain", b =>
                {
                    b.HasOne("PSMModel.Models.LightPost", "LightPost")
                        .WithMany()
                        .HasForeignKey("LightPostNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LightPost");
                });

            modelBuilder.Entity("PSMModel.Models.ProjectComplain", b =>
                {
                    b.HasOne("PSMModel.Models.Project", "Project")
                        .WithMany("ProjectComplains")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PSMModel.Models.Project", b =>
                {
                    b.Navigation("ProjectComplains");
                });

            modelBuilder.Entity("PSMModel.Models.Ride", b =>
                {
                    b.Navigation("RidePoints");
                });

            modelBuilder.Entity("PSMModel.Models.Ticket", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("TicketPackages");
                });

            modelBuilder.Entity("PSMModel.Models.Workpackage", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TicketPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
